$(document).ready(function()
{
  $("#view").click(function()
{
  $("#hideToggle").toggle(800);
  $("#showToggle").toggle(800);
});
$("#view1").click(function()
{
  $("#hideToggle").toggle(800);
$("#showToggle").toggle(800);
});
$("#view2").click(function()
{
  $("#hideToggle").toggle(800);
$("#showToggle").toggle(800);
});
$("#core").click(function()
{
  $("#flipShow").toggle(800);
$("#flipHide").toggle(800);
});
});
